apiVersion: app.example.com/v1
kind: AppService
metadata:
  name: apache
spec:
  size: 1
  image: docker.io/s994686229/microservice-kubernetes-demo-apache:latest
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
---
apiVersion: app.example.com/v1
kind: AppService
metadata:
  name: catalog
spec:
  size: 1
  image: s994686229/microservice-kubernetes-demo-catalog:latest
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30003
---
apiVersion: app.example.com/v1
kind: AppService
metadata:
  name: customer
spec:
  size: 1
  image: s994686229/microservice-kubernetes-demo-customer:latest
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
---
apiVersion: app.example.com/v1
kind: AppService
metadata:
  name: order
spec:
  size: 1
  image: s994686229/microservice-kubernetes-demo-order:latest
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30005